### ISSUE TITLE
Gerudoku Nether Update Textures

### ISSUE THREAD

**Issue by Jebzalis** [Syberiyxx/GeruDoku#1]
Since gerudoku doesn't have the new 1.16 textures I can make art for the new nether update textures, i've already made a few as examples (the shroomlight I should probably redo lol)
netherite sword
![netherite_sword](https://user-images.githubusercontent.com/69292829/89509673-36572080-d795-11ea-9dc3-80f12f510ffd.png)
crying obsidian
![crying_obsidian](https://user-images.githubusercontent.com/69292829/89509688-3e16c500-d795-11ea-90f8-9647b3d767d3.png)
shroomlight
![shroomlight](https://user-images.githubusercontent.com/69292829/89509744-4f5fd180-d795-11ea-8695-a85010ec32a0.png)

**Comment by sybenx** [comment]
I can integrate art you contribute. Be aware your art may be altered or replaced. I'll try to insure the pack maintains consistent styling. I can integrate the shroomlight as you've provided or wait if you'd like to change it. Once your art is integrated I'll add your name to the list of contributors in the pack.

**Comment by Jebzalis** [comment]
new round of textures, also the shroomlight can stay the way it is if you think it works well with the pack
[textures.zip](https://github.com/Syberiyxx/GeruDoku/files/5038019/textures.zip)

**Comment by sybenx** [comment]
pushed out an update including your textures

**Comment by Jebzalis** [comment]
neat thing i found, someone found the custom gerudoku pack that the yogscast used for the later half of shadow of israphel (around episode 30 and onwards)
https://www.planetminecraft.com/texture-pack/yogsremix-v8-91-official-yogscast-shadow-of-israphel-texture-pack-for-minecraft-1-1/

**Comment by Jebzalis** [comment]
netherite tools and armor, warped and crimson stuff, lodestone, plus the old pumpkin blur and old blue slime textures if you wanna include those last two as alt textures
[netherite.zip](https://github.com/Syberiyxx/GeruDoku/files/5072559/netherite.zip)

**Comment by sybenx** [comment]
I added the textures, I'll push out an update shortly. @Jebzalis 

edit: update pushed.

**Comment by Jebzalis** [comment]
new crimson and warped doors also oak trapdoor has correct naming
[doorz.zip](https://github.com/Syberiyxx/GeruDoku/files/5120993/doorz.zip)

**Comment by Jebzalis** [comment]
[schtuff and bees.zip](https://github.com/Syberiyxx/GeruDoku/files/5140329/schtuff.and.bees.zip)
new round of textures

**Comment by Jebzalis** [comment]
portals renamed to display properly
[portal.zip](https://github.com/Syberiyxx/GeruDoku/files/5140603/portal.zip)

**Comment by sybenx** [comment]
I've added many of your textures without modification. I altered the jungle and spruce trapdoors (circular jungle hole with, and slightly altered handle on the spruce trapdoor), angry bee (made the eyes more red), bell (more polished looking), and blast furnace (redder flame and slight glow). The face of the zombified piglin wasn't centered so I centered it.

**Comment by Jebzalis** [comment]
took a few screenshots of the pack.png world with gerudoku on if you wanna use em for anything like the planet minecraft page or something
[packpngart.zip](https://github.com/Syberiyxx/GeruDoku/files/5185626/packpngart.zip)

**Comment by sybenx** [comment]
Looks fantastic! I'll add them

**Comment by Goose192** [comment]
Are the Polished Blackstone Bricks and variations untextured, or is there textures which have been accidently left out?

**Comment by sybenx** [comment]
somehow I have _cracked_ polished blackstone bricks but not polished blackstone bricks

**Comment by sybenx** [comment]
I erased the cracks to make a polished blackstone bricks texture. If you have the original, I'll replace the one I just made. The walls, stairs and slab will all be updated as well.

**Comment by Goose192** [comment]
I dont have the original im afraid

**Comment by sybenx** [comment]
im closing this thread to keep things clean. open a new issue if you'd like to contribute more textures or find an issue with the pack @Jebzalis
