### ISSUE TITLE
Bugged Textures

### ISSUE THREAD

**Issue by Goose192** [Syberiyxx/GeruDoku#16]
Some items which already have textures but changed names need updating.

These include:

-White Dye
-Blue Dye
-Brown Dye
-Green Dye
-Yellow Dye
-Red Dye
-Black Dye

-Light Grey Bed

-Pufferfish
-Tropical Fish

-Popped Chorus Fruit (?)

These are just the ones I could Find. Thanks guys

**Comment by sybenx** [comment]
thanks! These are all fixed and will be pushed out in the next release
