### ISSUE TITLE
Incorrect Nether Textures

### ISSUE THREAD

**Issue by Goose192** [Syberiyxx/GeruDoku#17]
Some of the textures associated with the nether have had names changed and need updating.

-Nether Brick
-Nether Brick Slabs
-Nether Brick walls
-Nether Brick Fence
-Nether Brick stairs

Also, the 'Red Nether' variant of the regular Nether Brick can be textured by a slight recolour of Nether Brick Textures, if someone is up to it. Thanks guys

**Comment by sybenx** [comment]
done, will be added to next update
