### ISSUE TITLE
turtles

### ISSUE THREAD

**Issue by sybenx** [Syberiyxx/GeruDoku#19]
- [x] -turtles
- [x] -turtle shell (helmet)
- [x] -turtle egg item
- [x] -turtle egg
- [x] -sea pickle
- [x] kelp
- [x] kelp block
- [x] coral
- [x] sea grass

**Comment by Goose192** [comment]
I stripped the turtle texture from the discontinued BaryDoku texture pack. You I'm gonna check if their are any other 1.13 textures we can borrow from it. cheers.
![big_sea_turtle](https://user-images.githubusercontent.com/71587237/98965455-fa54f980-2501-11eb-8d7f-3b651ddcfdcb.png)

**Comment by Goose192** [comment]
Aight, I have found some more textures that can be stripped, but I'm really not familiar with where to find them in the pack.

-Sea Pickle
-Sea Grass
-Dried kelp
-lots of different Coral Textures
-conduit

these are the ones I could find. If you think they don't fit with the pack very well, then leave them out, I just thought I'd point them out. Cheers dude

**Comment by Goose192** [comment]
Oh and the link to the pack download is at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/2895569-gerudoku-legacy-thread-1-14-coming-soon-32x if you need it

**Comment by windowslogic** [comment]
Found some fitting turtle egg and turtle egg item textures.
![turtle_egg](https://user-images.githubusercontent.com/39615739/128605560-c053daee-9d58-43f5-a75c-a9e64050261e.png)
![turtle_egg](https://user-images.githubusercontent.com/39615739/128605705-186c43fa-fcf8-45f7-bdb3-43fa72b8c030.png)
![turtle_egg_not_cracked](https://user-images.githubusercontent.com/39615739/128605706-42c1938d-13f2-4e4f-8a30-d507bae70a43.png)
![turtle_egg_slightly_cracked](https://user-images.githubusercontent.com/39615739/128605707-d6e1028d-facc-48d4-8c12-5a2d45c16c7c.png)
![turtle_egg_very_cracked](https://user-images.githubusercontent.com/39615739/128605709-172c0aab-c529-41c2-a195-2a7c87c2802e.png)

**Comment by windowslogic** [comment]
This needs to be closed as the Turtle Egg item and block texture was added.
