### ISSUE TITLE
Better Smithing Table Texture

### ISSUE THREAD

**Issue by windowslogic** [Syberiyxx/GeruDoku#28]
A better Smithing Table texture than the one added previously.

![smithing_table_bottom](https://user-images.githubusercontent.com/39615739/110225755-580db700-7ee0-11eb-8c35-4d5bc9fe32d9.png)
![smithing_table_front](https://user-images.githubusercontent.com/39615739/110225756-580db700-7ee0-11eb-9d05-beef48a04077.png)
![smithing_table_side](https://user-images.githubusercontent.com/39615739/110225758-58a64d80-7ee0-11eb-9243-06988ba31e5f.png)

**Comment by windowslogic** [comment]
![smithing_table_top](https://user-images.githubusercontent.com/39615739/110225766-6a87f080-7ee0-11eb-88c2-da3061a92a56.png)

**Comment by sybenx** [comment]
added for next update
