### ISSUE TITLE
Better Stone Cutter Textures (Base only)

### ISSUE THREAD

**Issue by windowslogic** [Syberiyxx/GeruDoku#32]
I made a better Stone Cutter texture which fits GeruDoku more.

![stonecutter_side](https://user-images.githubusercontent.com/39615739/110338354-d1abbf00-801e-11eb-8c78-8e871fe3d12f.png)
![stonecutter_top](https://user-images.githubusercontent.com/39615739/110338356-d1abbf00-801e-11eb-91f0-210f534174f8.png)

**Comment by sybenx** [comment]
added for next version
