### ISSUE TITLE
Better Barrel Texture

### ISSUE THREAD

**Issue by windowslogic** [Syberiyxx/GeruDoku#33]
A nicer barrel texture that fits the style of GeruDoku.

![barrel_top_open](https://user-images.githubusercontent.com/39615739/110338528-00c23080-801f-11eb-8e31-639b8fc1cdd2.png)
![barrel_bottom](https://user-images.githubusercontent.com/39615739/110338531-015ac700-801f-11eb-8404-a3ad70a43be9.png)
![barrel_side](https://user-images.githubusercontent.com/39615739/110338533-015ac700-801f-11eb-868c-069036151caa.png)
![barrel_top](https://user-images.githubusercontent.com/39615739/110338534-015ac700-801f-11eb-94e3-a51e3251a778.png)

**Comment by windowslogic** [comment]
Will most likely improve the textures in the future.

**Comment by sybenx** [comment]
added for next release
