### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by sybenx** [Syberiyxx/GeruDoku#37]
"The grass and dirt don't seem to connect very well personally, and dirt being randomly rotated on flat ground is a bit weird, podzol looks awful with the colour imo, other than those it's so nice to see someone updating this resource pack, mad respect"

ReachTea
https://www.curseforge.com/minecraft/texture-packs/gerudoku?comment=27

**Comment by windowslogic** [comment]
More detailed grass textures produced from using the older Beta 1.7 textures.
![grass_path_top](https://user-images.githubusercontent.com/39615739/128605932-18dcc952-ffab-4160-ac01-9454b8c294f9.png)
![grass_block_top](https://user-images.githubusercontent.com/39615739/128605934-38343cbc-4eaf-49f5-85de-11ca6096bf3e.png)

**Comment by sybenx** [comment]
dirt rotation is fixed, podzol updated, ty for the old textures, to my eye the current grass textures look more similar to the ones used in old yogscast videos
