### ISSUE TITLE
A bunch of other stuff redone/done.

### ISSUE THREAD

**Issue by windowslogic** [Syberiyxx/GeruDoku#38]
[soul blocks.zip](https://github.com/Syberiyxx/GeruDoku/files/6949376/soul.blocks.zip)
![soul_lantern](https://user-images.githubusercontent.com/39615739/128607066-f340bae0-4c65-448c-b567-abc2db518a9f.png)
![soul_campfire](https://user-images.githubusercontent.com/39615739/128607069-4004b711-e992-4697-95f6-565669f9da38.png)
![campfire](https://user-images.githubusercontent.com/39615739/128607084-22306d25-5e94-4aff-9ad5-9d30f02cb081.png)
![honeycomb](https://user-images.githubusercontent.com/39615739/128607107-ffde084e-ca82-4ea5-a17b-0ffa438225be.png)
![crystallized_honey](https://user-images.githubusercontent.com/39615739/128607109-0e9b4179-b07b-4a7c-8d42-d47465b0115c.png)
![netherite_axe](https://user-images.githubusercontent.com/39615739/128607159-a5d939dd-6aaa-4a9b-adf6-892a30c0d2ee.png)
![netherite_boots](https://user-images.githubusercontent.com/39615739/128607161-404072f8-f065-4828-a0e9-897f03a69b29.png)
![netherite_chestplate](https://user-images.githubusercontent.com/39615739/128607162-af397c57-9579-46dc-853f-46661bdca5cd.png)
![netherite_helmet](https://user-images.githubusercontent.com/39615739/128607163-57b43dda-f0d0-498a-9e59-71832ca39471.png)
![netherite_hoe](https://user-images.githubusercontent.com/39615739/128607164-a27eccec-1779-4e34-8f45-5b358f828f61.png)
![netherite_ingot](https://user-images.githubusercontent.com/39615739/128607165-6529aefd-fbbd-4191-87ba-20dd5cb2aaa8.png)
![netherite_leggings](https://user-images.githubusercontent.com/39615739/128607166-aa814c51-615e-4dd4-bf39-dd402c677aa3.png)
![netherite_pickaxe](https://user-images.githubusercontent.com/39615739/128607169-5c55067d-afb8-4370-bd59-9b44e482aebd.png)
![netherite_scrap](https://user-images.githubusercontent.com/39615739/128607170-9f682339-a354-4338-9eed-5f61e5a2cb4e.png)
![netherite_shovel](https://user-images.githubusercontent.com/39615739/128607172-ea5aa4e2-471c-4c9f-8089-3d2bece1250b.png)
[netherite sword.zip](https://github.com/Syberiyxx/GeruDoku/files/6949403/netherite.sword.zip)
![sweet_berries](https://user-images.githubusercontent.com/39615739/128607236-0f6eeb8a-e30f-4252-b853-15f810e67554.png)
![bell](https://user-images.githubusercontent.com/39615739/128607269-0be46cb1-ce16-4593-be84-f9210e3300fd.png)
[bee blocks.zip](https://github.com/Syberiyxx/GeruDoku/files/6949408/bee.blocks.zip)
[coral blocks.zip](https://github.com/Syberiyxx/GeruDoku/files/6949413/coral.blocks.zip)
![bell_body](https://user-images.githubusercontent.com/39615739/128607440-4ddd63fb-ee18-420f-8774-aaa6be25d8a9.png)

**Comment by sybenx** [comment]
great work! added for next update
