### ISSUE TITLE
New gui textures

### ISSUE THREAD

**Issue by TimelapsedEon** [Syberiyxx/GeruDoku#4]
Made some new guis. Reused resources where possible. Had to make an adjustment to widgets.png to make villager2.png work visually. Enjoy. -TimelapsedEon

![blast_furnace](https://user-images.githubusercontent.com/68088516/91126271-9bee4c80-e671-11ea-9e56-64e7bf2fed03.png)
![cartography_table](https://user-images.githubusercontent.com/68088516/91126272-9bee4c80-e671-11ea-9b10-f89ec15c8aba.png)
![gamemode_switcher](https://user-images.githubusercontent.com/68088516/91126273-9c86e300-e671-11ea-8060-576e34f8b0b9.png)
![grindstone](https://user-images.githubusercontent.com/68088516/91126274-9c86e300-e671-11ea-8d6d-97259d0966aa.png)
![loom](https://user-images.githubusercontent.com/68088516/91126275-9c86e300-e671-11ea-9402-4dc7f807fe35.png)
![smithing](https://user-images.githubusercontent.com/68088516/91126276-9c86e300-e671-11ea-8897-c59d0cb02f2d.png)
![smoker](https://user-images.githubusercontent.com/68088516/91126277-9c86e300-e671-11ea-81f7-9e23aa4ab59b.png)
![villager2](https://user-images.githubusercontent.com/68088516/91126278-9d1f7980-e671-11ea-8267-ab81bb9bed86.png)
![widgets](https://user-images.githubusercontent.com/68088516/91126300-aa3c6880-e671-11ea-8bae-cf304caf6c08.png)

**Comment by Syberiyxx** [comment]
- [ ] anvil.png
- [ ] beacon.png
- [ ] blast_furnace.png
- [ ] brewing_stand.png
- [ ] cartography_table.png
- [ ] crafting_table.png
- [ ] dispenser.png
- [ ] enchanting_table.png
- [ ] furnace.png
- [ ] gamemode_switcher.png
- [ ] generic_54.png
- [ ] grindstone.png
- [ ] hopper.png
- [ ] horse.png
- [ ] inventory.png
- [ ] loom.png
- [ ] shulker_box.png
- [ ] smithing.png
- [ ] smoker.png
- [ ] stats_icons.png
- [ ] stonecutter.png
- [ ] villager2.png

**Comment by sybenx** [comment]
I've added the GUI's you've provided and pushed out an update to GeruDoku. Apologies for failing to credit you in the original release notes. I've updated the release notes to acknowledge your contribution.
