### ISSUE TITLE
Restored villagers 

### ISSUE THREAD

**Issue by Voidatron** [Syberiyxx/GeruDoku#49]
[zombie_villager.zip](https://github.com/sybenx/GeruDoku/files/8872978/zombie_villager.zip)
[villager.zip](https://github.com/sybenx/GeruDoku/files/8872979/villager.zip)

The zombie villagers were broken so I planned on fixing them, but when I opened the file I found that there were profession pngs that were unused, so I added them to the pack and fixed all villagers and professions. There are not any new textures made by me, I just did lots of file renaming and re-organizing.

**Comment by sybenx** [comment]
added
