### ISSUE TITLE
User Interface GUI's

### ISSUE THREAD

**Issue by sybenx** [Syberiyxx/GeruDoku#5]
- [x] anvil.png
- [x] beacon.png
- [x] blast_furnace.png
- [x] brewing_stand.png
- [x] cartography_table.png
- [x] crafting_table.png
- [x] dispenser.png
- [x] enchanting_table.png
- [x] furnace.png
- [x] gamemode_switcher.png
- [x] generic_54.png
- [x] grindstone.png
- [x] hopper.png
- [x] horse.png
- [x] inventory.png
- [x] loom.png
- [x] shulker_box.png
- [x] smithing.png
- [x] smoker.png
- [x] stats_icons.png
- [x] stonecutter.png
- [x] villager2.png

**Comment by TimelapsedEon** [comment]
Stonecutter gui
![stonecutter](https://user-images.githubusercontent.com/68088516/91351877-ffce5d80-e7b6-11ea-92b0-abcc59886a70.png)

**Comment by sybenx** [comment]
I've added this gui and pushed out an update.
