### ISSUE TITLE
Copper ore texture too much like gold ore texture

### ISSUE THREAD

**Issue by Dybdal** [Syberiyxx/GeruDoku#50]
I have made some new textures for stone copper ore and deepslate copper ore: 
![copper_ore](https://user-images.githubusercontent.com/70016986/175830246-fb66d5c3-b3bc-43dd-9658-115bd2673e40.png)

![deepslate_copper_ore](https://user-images.githubusercontent.com/70016986/175830249-244f3c9c-0fbc-4ce9-83f3-3a231b583269.png)

I made them using parts of the existing gold texture and rearranging them to fit the look of copper in the default minecraft texturepack more closely. I think this is a big improvement, as it makes it a lot easier to differientiate between copper and gold in deep caves, especially with shaders on. Feel free to use the textures if they're up to standard.

**Comment by sybenx** [comment]
added
