### ISSUE TITLE
Crafting Block Textures

### ISSUE THREAD

**Issue by sybenx** [Syberiyxx/GeruDoku#6]
- [x] Cartography Table
- [x] Loom
- [x] Blast Furnace
- [x] Barrel
- [x] Lectern
- [x] Smithing Table
- [x] Fletching Table

**Comment by Jebzalis** [comment]
[blastfurnace.zip](https://github.com/Syberiyxx/GeruDoku/files/5140370/blastfurnace.zip)

**Comment by Jebzalis** [comment]
barrels were missing as well i think
[barrel.zip](https://github.com/Syberiyxx/GeruDoku/files/5140537/barrel.zip)

**Comment by sybenx** [comment]
i forgot to add barrels in the 1.4 update. I'll add it to the next

**Comment by Jebzalis** [comment]
loom, cartography, smithing and missing lectern stuff
[new stuff.zip](https://github.com/Syberiyxx/GeruDoku/files/5165775/new.stuff.zip)

**Comment by sybenx** [comment]
added! will be pushed out in 1.4.2

**Comment by sybenx** [comment]
i stretched your barrel textures and added metal

**Comment by windowslogic** [comment]
Found/created some better textures for things. Take a look and see if they fit with GeruDoku.
[blast furnace.zip](https://github.com/Syberiyxx/GeruDoku/files/6949342/blast.furnace.zip)
[cartography table.zip](https://github.com/Syberiyxx/GeruDoku/files/6949344/cartography.table.zip) (Is almost the same, but the book on top looks better.)
[fletching table.zip](https://github.com/Syberiyxx/GeruDoku/files/6949347/fletching.table.zip)
[loom.zip](https://github.com/Syberiyxx/GeruDoku/files/6949348/loom.zip)
[smoker.zip](https://github.com/Syberiyxx/GeruDoku/files/6949350/smoker.zip)
