### ISSUE TITLE
boats

### ISSUE THREAD

**Issue by sybenx** [Syberiyxx/GeruDoku#7]
- [ ] oak
- [ ] spruce
- [ ] birch
- [ ] acacia
- [ ] jungle
- [ ] dark oak

**Comment by windowslogic** [comment]
Fixed boat textures.
![acacia](https://user-images.githubusercontent.com/39615739/128605859-b370a682-e60b-487c-bdc4-dcf89d253d18.png)
![birch](https://user-images.githubusercontent.com/39615739/128605860-acd49362-8874-4a94-8cb2-e06a5ec9e41a.png)
![dark_oak](https://user-images.githubusercontent.com/39615739/128605861-d0ac6b73-f379-48e7-9f94-12807311d7a4.png)
![jungle](https://user-images.githubusercontent.com/39615739/128605862-ea2e80dd-ca9c-4d53-bca3-3a65b05ff3c7.png)
![oak](https://user-images.githubusercontent.com/39615739/128605863-c0b86610-20d7-4003-ae20-958a934d00a2.png)
![spruce](https://user-images.githubusercontent.com/39615739/128605864-e7e57d11-5747-4e5b-9540-2b5cecc58345.png)

**Comment by sybenx** [comment]
adding for next update
