### ISSUE TITLE
Mainly Banners and Shields 

### ISSUE THREAD

**Issue by JDHD99** [Syberiyxx/GeruDoku#9]
One of the main texture issues I see is that whenever someone designs a banner or a shield, the textures on the shield mainly are slightly broken or out of place (Perhaps the resolution is a little bit off, just thought I'd bring this up) Thank you for updating my favorite texture pack! 
![unknown (1)](https://user-images.githubusercontent.com/70789224/92297391-2bed9980-ef82-11ea-97a0-b57e59b3d415.png)
![unknown](https://user-images.githubusercontent.com/70789224/92297393-2e4ff380-ef82-11ea-9cd3-8896272ef925.png)

**Comment by sybenx** [comment]
Thanks for pointing this out! I'll start working on fixing it

**Comment by sybenx** [comment]
fixed in 1.4.1 and above
